### ISSUE TITLE
Can't find results.

### ISSUE THREAD

**Issue by ahagacv** [DreiDe/GWP---Get-Whatsapp-Pictures#1]
Hi,

When I run the extension, everything seems to work fine. However, I can't find the results in the database. Could you please help me with that? Can you show me what are the configurations of your mysql database?

**Comment by piorphism** [comment]
I am facing the same issue when trying to save into the database.

**Comment by DreiDe** [comment]
OK, I had time now to look for this issue. For me everything works just fine but I can think of two reasons causing the problem:
The first could be a wrong configuration of the MySql Database. To make this easier I uploaded [whatsapp_db.sql](https://github.com/DreiDe/GWP---Get-Whatsapp-Pictures/blob/master/whatsapp_db.sql).  (Just download and import e.g. with PhpMyAdmin)
The second thing could be a missconfiguration of one of the files, eighter with [whatsapp.php](https://github.com/DreiDe/GWP---Get-Whatsapp-Pictures/blob/master/gwp/whatsapp.php) (wrong username or password) or with [manifest.json](https://github.com/DreiDe/GWP---Get-Whatsapp-Pictures/blob/master/gwp/manifest.json) if your Database is not at localhost. If so you have to grand permission to the plugin to access your external server by adding '"<your_server>/*",' under '"http://localhost/*",' and readd the plugin afterwards.

Do you get the pictures in the pics folder?

I hope I could help. Please reply if this fixed your problem.

**Comment by ahagacv** [comment]
Now it works. Thanks. But I have another question. How do you manage to run the script multiple times from different phone numbers. 
For example, after first successful run, my number got banned and I tried to run the script by logging from different phone number. However, my new phone number got banned the moment I tried to scan the QR code. I didn't even run the script. Is it because of the same IP address?

How can I solve this issue (maybe adding proxies list to the script)?

**Comment by piorphism** [comment]
Oh, thanks, it works fine now. I am new to scraping and I am facing the same issue. My 3 phone numbers were blocked instantly. What can I do about it? And what was your strategy to avoid banning?

**Comment by DreiDe** [comment]
The reason for this problem is propably the public IP, maybe also the MAC address. But it should be possible to bypass this with a proxy easily. 
At the moment no proxy feature is build in the project. It could be included by using the  chrome.proxy API. But for now it should be easier by just using another Chrome Plugin like [SwitchyOmega](https://chrome.google.com/webstore/detail/proxy-switchyomega/padekgcemlokbadohgkifijomclgjgif) or [FoxyProxy](https://chrome.google.com/webstore/detail/foxyproxy-standard/gcknhkkoolaabfmlnjonogaaifnjlfnp). If you are running Linux it also shouldn't be hard to write a python script to switch the proxy after x minutes.
